kujaff\CryptoCurrenciesBundle\Entity\Currency:
    type: entity
    table: cryptocurrencies
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        tag:
            type: string
            length: '5'
        name:
            type: string
            length: '20'
        algorithm:
            type: smallint
        difficulty:
            type: decimal
            precision: 10
            scale: 10
            nullable: true
    lifecycleCallbacks: {  }
