services:
    cryptocurrencies.installer:
        class: kujaff\CryptoCurrenciesBundle\Install\Installer
        arguments: [@service_container]
        tags:
            - { name: bundle.install }
            - { name: bundle.update }
            - { name: bundle.uninstall }